name: ime_international_phone_input
description: A simple and customizable flutter package for inputting phone number in intl / international format uses Google's libphonenumber.
version: 0.0.1
repository: https://github.com/R0shish/ime_international_phone_input

environment:
  sdk: ">=3.0.2 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  equatable: ^2.0.5
  collection: ^1.18.0
  dlibphonenumber: ^1.1.35

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - assets/flags/
